// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fndhlbcixdppruurhzkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZGhsYmNpeGRwcHJ1dXJoemtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzODkwNTQsImV4cCI6MjA1Mzk2NTA1NH0.lFuUzGjbekF2NAMBEdCKohBLdq8m6KCfvIwsBp4svak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);